ALTER TABLE issues ADD COLUMN IF NOT EXISTS estimate_minutes INT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS labels JSONB DEFAULT '[]';
ALTER TABLE agents ADD COLUMN IF NOT EXISTS model TEXT DEFAULT '';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS branch_name TEXT DEFAULT '';
