ALTER TABLE tasks DROP COLUMN IF EXISTS branch_name;
ALTER TABLE agents DROP COLUMN IF EXISTS model;
ALTER TABLE issues DROP COLUMN IF EXISTS labels;
ALTER TABLE issues DROP COLUMN IF EXISTS estimate_minutes;
